update script.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,5 +22,11 @@ jobs:
           key: ${{ secrets.KEY }}
           port: 22
           script: |
-            # Change directory to where deploy.sh is located, then run it.
-            cd /root/server/lexomat && ./deploy.sh
+            # Verify the deploy.sh script exists
+            if [ -f /root/server/lexomat/deploy.sh ]; then
+              echo "deploy.sh found"
+              cd /root/server/lexomat && ./deploy.sh
+            else
+              echo "deploy.sh not found"
+              exit 1
+            fi
